Enable script linting. (#1797)
- Fix linting errors.

diff --git a/scripts/tools/linux-install-bazel b/scripts/tools/linux-install-bazel
--- a/scripts/tools/linux-install-bazel
+++ b/scripts/tools/linux-install-bazel
@@ -6,7 +6,8 @@ if [[ "$(uname)" != "Linux" ]]; then
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
 # Use Bazelisk launcher for Bazel (automatically downloads required version of Bazel).
 BAZELISK_VERSION="v1.0"
@@ -16,6 +17,7 @@ BAZELISK_URL="${BAZELISK_BASE_URL}/${BAZELISK_VERSION}/${BAZELISK_BIN}"
 BAZELISK_DIRECTORY="${TOOLS_DIR}/bazelisk"
 
 function update_bazel() {
+  # shellcheck disable=SC2155
   local bazel_current="$(bazel version | grep -oh 'Bazelisk version: v[0-9]*\.[0-9]*')" \
     || bazel_current='none'
 
@@ -35,7 +37,7 @@ function update_bazel() {
   USE_BAZEL_VERSION=0.26.1 ${BAZEL} version # release-1.2
   USE_BAZEL_VERSION=0.28.1 ${BAZEL} version # release-1.3
 
-  ${SUDO} ${BAZEL} shutdown
-  ${SUDO} rm -rf ${HOME}/.cache/bazel
+  ${SUDO} "${BAZEL}" shutdown
+  ${SUDO} rm -rf "${HOME}"/.cache/bazel
   echo 'Bazelisk up-to-date.'
 }
diff --git a/scripts/tools/linux-install-docker b/scripts/tools/linux-install-docker
--- a/scripts/tools/linux-install-docker
+++ b/scripts/tools/linux-install-docker
@@ -7,7 +7,8 @@ if [[ "$(uname)" != "Linux" ]]; then
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
 #Version: 18.06.1~ce-0~ubuntu-xenial
 DOCKER_VERSION=18.06.1
@@ -19,14 +20,12 @@ XENIAL_REPO='ubuntu'
 # CE
 XENIAL_VERSION_SUFFIX="~ce~3-0~${XENIAL_REPO}"
 # Default
-REPO="${XENIAL_REPO}"
 VERSION_SUFFIX="${XENIAL_VERSION_SUFFIX}"
 
 function set_platform_env() {
   local platform="${1}"
   case "${platform}" in
     'ubuntu-16-04')
-      REPO="${XENIAL_REPO}"
       VERSION_SUFFIX="${XENIAL_VERSION_SUFFIX}";;
     *) error_exit "Plaform ${platform} is not supported."
   esac
@@ -56,6 +55,7 @@ function update_apt() {
 }
 
 function update_docker() {
+  # shellcheck disable=SC2155
   local version="$(docker --version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')"
   if [[ "${version}" != "${DOCKER_VERSION}" ]]; then
     local platform="${1}"
diff --git a/scripts/tools/linux-install-gcloud b/scripts/tools/linux-install-gcloud
--- a/scripts/tools/linux-install-gcloud
+++ b/scripts/tools/linux-install-gcloud
@@ -7,13 +7,11 @@ if [[ "$(uname)" != "Linux" ]]; then
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
-
-GCLOUD_URL='https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.zip'
 
 function install_gcloud() {
-  CLOUDSDK_PYTHON_SITEPACKAGES=1
   ${SUDO} rm -rf /usr/lib/google-cloud-sdk \
   && export CLOUDSDK_CORE_DISABLE_PROMPTS=1 \
   && export CLOUDSDK_INSTALL_DIR=/usr/lib/ \
@@ -35,7 +33,7 @@ function update_gcloud() {
     || error_exit 'Could not install gcloud'
   echo "Updating gcloud."
   ${SUDO} sed -i -e 's/true/false/' /usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/config.json
-  ${SUDO} ${GCLOUD} -q components update kubectl beta \
+  ${SUDO} "${GCLOUD}" -q components update kubectl beta \
     || error_exit 'Cannot update gcloud'
 }
 
diff --git a/scripts/tools/linux-install-golang b/scripts/tools/linux-install-golang
--- a/scripts/tools/linux-install-golang
+++ b/scripts/tools/linux-install-golang
@@ -6,7 +6,8 @@ if [[ "$(uname)" != "Linux" ]]; then
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
 GO_VERSION='1.12.5'
 GO_BASE_URL="https://storage.googleapis.com/golang"
@@ -27,6 +28,7 @@ function install_go_pkg() {
 }
 
 function update_go() {
+  # shellcheck disable=SC2155
   local go_current="$(go version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')" \
     || go_current='none'
 
diff --git a/scripts/tools/linux-install-ninja b/scripts/tools/linux-install-ninja
--- a/scripts/tools/linux-install-ninja
+++ b/scripts/tools/linux-install-ninja
@@ -6,7 +6,8 @@ if [[ "$(uname)" != "Linux" ]]; then
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
 NINJA_VERSION='1.9.0'
 NINJA_BASE_URL="https://github.com/ninja-build/ninja/releases/download/v${NINJA_VERSION}"
diff --git a/scripts/tools/linux-install-protoc b/scripts/tools/linux-install-protoc
--- a/scripts/tools/linux-install-protoc
+++ b/scripts/tools/linux-install-protoc
@@ -6,7 +6,8 @@ if [[ "$(uname)" != "Linux" ]]; then
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
 PROTOC_VERSION="3.5.0"
 PROTOC_ARCHIVE="protoc-${PROTOC_VERSION}-linux-x86_64.zip"
@@ -16,6 +17,7 @@ PROTOC_BINARY='protoc'
 PROTOC_DIRECTORY="${TOOLS_DIR}/protoc"
 
 function update_protoc() {
+  # shellcheck disable=SC2155
   local protoc_current="$(protoc --version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')" \
     || protoc_current='none'
   if [[ "${PROTOC_VERSION}" == "${protoc_current}" ]]; then
@@ -25,12 +27,13 @@ function update_protoc() {
   mkdir -p "${PROTOC_DIRECTORY}"
   retry -n 3 wget -q -nc -P "${PROTOC_DIRECTORY}" "${PROTOC_URL}" \
     || error_exit 'Could not download protoc.'
-  (cd ${PROTOC_DIRECTORY}; unzip  ${PROTOC_ARCHIVE} )
+  # shellcheck disable=SC2164
+  (cd "${PROTOC_DIRECTORY}"; unzip  ${PROTOC_ARCHIVE} )
   ${SUDO} cp -f "${PROTOC_DIRECTORY}/bin/${PROTOC_BINARY}" /usr/local/bin/protoc \
     || error_exit 'Could not install protoc.'
   ${SUDO} chmod +x /usr/local/bin/protoc \
     || error_exit 'Could not change permission on protoc'
-  ${SUDO} cp -fr ${PROTOC_DIRECTORY}/include/* /usr/local/include/ \
+  ${SUDO} cp -fr "${PROTOC_DIRECTORY}"/include/* /usr/local/include/ \
     || error_exit 'Could not copy protoc include files'
   ${SUDO} chmod -R 755  /usr/local/include/google/ \
     || error_exit 'Could not change permission on protoc include files'
diff --git a/scripts/tools/linux-install-repo b/scripts/tools/linux-install-repo
--- a/scripts/tools/linux-install-repo
+++ b/scripts/tools/linux-install-repo
@@ -6,13 +6,16 @@ if [[ "$(uname)" != "Linux" ]]; then
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
 REPO_URL="https://storage.googleapis.com/git-repo-downloads/repo"
 REPO_BINARY='repo'
 REPO_DIRECTORY="${TOOLS_DIR}/repo"
 
 function update_repo() {
+  # shellcheck disable=SC2034
+  # shellcheck disable=SC2155
   local repo_current="$(repo --version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')" \
     || repo_current='none'
 
diff --git a/scripts/tools/linux-install-wrk b/scripts/tools/linux-install-wrk
--- a/scripts/tools/linux-install-wrk
+++ b/scripts/tools/linux-install-wrk
@@ -6,7 +6,8 @@ if [[ "$(uname)" != "Linux" ]]; then
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
 WRK_VERSION='4.0.2'
 WRK_BASE_URL="https://storage.googleapis.com/istio-tools/wrk"
@@ -15,6 +16,7 @@ WRK_URL="${WRK_BASE_URL}/${WRK_BINARY}"
 WRK_DIRECTORY="${TOOLS_DIR}/wrk"
 
 function update_wrk() {
+  # shellcheck disable=SC2155
   local wrk_current="$(wrk --version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')" \
     || wrk_current='none'
 
