Adds pipeline phase for slave update.

diff --git a/jenkins/slaves/slave-test b/jenkins/slaves/slave-test
--- a/jenkins/slaves/slave-test
+++ b/jenkins/slaves/slave-test
@@ -3,24 +3,24 @@
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 ESP_ROOT="$(cd "${DIR}/../.." && pwd)"
 
-. "${ESP_ROOT}"/script/jenkins-utilities || { echo "Cannot load Jenkins utilities" ; exit 1 ; }
+. "${ESP_ROOT}"/scripts/all-utilities || { echo "Cannot load utilities" ; exit 1 ; }
 
 echo 'Verifying Docker Install'
-run docker info || error_exit 'Docker is not installed properly'
-run docker version || error_exit 'Docker is not installed properly'
-run docker run hello-world || error_exit 'Docker is not installed properly'
+docker info || error_exit 'Docker is not installed properly'
+docker version || error_exit 'Docker is not installed properly'
+docker run hello-world || error_exit 'Docker is not installed properly'
 
 echo 'Verifying Bazel installation'
-run bazel version || error_exit 'Bazel is not installed properly'
+bazel version || error_exit 'Bazel is not installed properly'
 
 echo 'Verifying gcloud installation'
-run gcloud version || error_exit 'gcloud is not installed properly'
+gcloud version || error_exit 'gcloud is not installed properly'
 
 echo 'Verifying kubectl installation'
-run kubectl version || error_exit 'kubectl is not installed properly'
+kubectl version || error_exit 'kubectl is not installed properly'
 
 echo 'Verifying gsutil installation'
-run gsutil version || error_exit 'gsutil is not installed properly'
+gsutil version || error_exit 'gsutil is not installed properly'
 
 echo 'Verifying that the user is jenkins'
 THIS_USER="$(whoami)"
diff --git a/scripts/jenkins-build-docker-slave b/scripts/jenkins-build-docker-slave
--- a/scripts/jenkins-build-docker-slave
+++ b/scripts/jenkins-build-docker-slave
@@ -4,7 +4,7 @@
 #
 
 ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${ROOT}/script/jenkins-utilities || { echo "Cannot load Jenkins utilities"; exit 1; }
+. ${ROOT}/scripts/all-utilities || { echo "Cannot load Jenkins utilities"; exit 1; }
 
 BUILD=false
 PUSH=false
@@ -44,7 +44,7 @@ if [[ "${BUILD}" == true ]]; then
   update_image "${IMAGE}"
   if [[ ${?} -eq 0 ]]; then
     echo "Building docker image ${IMAGE}."
-    run retry -n 10 docker build --build-arg TOOLS_BUCKET="${TOOLS_BUCKET}" --no-cache -t ${IMAGE} \
+    retry -n 10 docker build --build-arg TOOLS_BUCKET="${TOOLS_BUCKET}" --no-cache -t ${IMAGE} \
       -f "${DOCKER_FILE}" . || error_exit "Could not build ${SLAVE}"
     echo "Pushing Docker image: ${IMAGE}"
     retry -n 3 ${GCLOUD} docker -- push "${IMAGE}" \
