Enable script linting.
- Fix linting errors.

diff --git a/scripts/cleanup-cache b/scripts/cleanup-cache
--- a/scripts/cleanup-cache
+++ b/scripts/cleanup-cache
@@ -3,7 +3,8 @@
 ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
 DIR="${ROOT}/scripts"
 
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
 ARGS=()
 
@@ -27,6 +28,7 @@ done
 function generate_job_yaml() {
   local node="${1}"
   local yaml="${2}"
+  # shellcheck disable=SC2206
   local uuids=(${node//-/ })
   local uuid="${uuids[-2]}-${uuids[-1]}"
   cp "${JOB_TEMPLATE}" "${yaml}"
@@ -42,15 +44,18 @@ function generate_job_yaml() {
 
 
 echo 'Getting credentials for Kubernetes cluster'
-gcloud container clusters get-credentials ${CLUSTER_NAME} ${ARGS[@]}\
+# shellcheck disable=SC2145
+# shellcheck disable=SC2068
+gcloud container clusters get-credentials "${CLUSTER_NAME}" ${ARGS[@]}\
   || error_exit 'Could not get kubectl config for cluster'
 
 CLUSTER_NODES="$(kubectl get nodes \
-  --selector=${SELECTOR} \
+  --selector="${SELECTOR}" \
   -o jsonpath='{.items[*].metadata.name}')"
 
 [[ -z "${CLUSTER_NODES}" ]] && error_exit 'Could not find Jenkins nodes.'
 
+# shellcheck disable=SC2068
 for CLUSTER_NODE in ${CLUSTER_NODES[@]}; do
   YAML="${TMP_DIR}/${CLUSTER_NODE}.yaml"
   generate_job_yaml "${CLUSTER_NODE}" "${YAML}"
diff --git a/scripts/linux-install-software b/scripts/linux-install-software
--- a/scripts/linux-install-software
+++ b/scripts/linux-install-software
@@ -7,20 +7,33 @@ if [[ "$(uname)" != "Linux" ]]; then
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 # TOOLS
-. ${DIR}/tools/linux-install-bazel || error_exit "Cannot load Bazel install script"
-. ${DIR}/tools/linux-install-clang || error_exit "Cannot load Clang install script"
-. ${DIR}/tools/linux-install-cmake || error_exit "Cannot load cmake install script"
-. ${DIR}/tools/linux-install-docker || error_exit "Cannot load Docker install script"
-. ${DIR}/tools/linux-install-gcloud || error_exit "Cannot load gcloud install script"
-. ${DIR}/tools/linux-install-golang || error_exit "Cannot load golang install script"
-. ${DIR}/tools/linux-install-ninja || error_exit "Cannot load ninja install script"
-. ${DIR}/tools/linux-install-repo || error_exit "Cannot load repo install script"
-. ${DIR}/tools/linux-install-wrk || error_exit "Cannot load wrk install script"
-. ${DIR}/tools/linux-install-protoc || error_exit "Cannot load protoc install script"
-. ${DIR}/tools/linux-install-helm || error_exit "Cannot load helm install script"
-. ${DIR}/tools/linux-install-gcc || error_exit "Cannot load gcc install script"
+# shellcheck disable=SC1090
+. "${DIR}"/tools/linux-install-bazel || error_exit "Cannot load Bazel install script"
+# shellcheck disable=SC1090
+. "${DIR}"/tools/linux-install-clang || error_exit "Cannot load Clang install script"
+# shellcheck disable=SC1090
+. "${DIR}"/tools/linux-install-cmake || error_exit "Cannot load cmake install script"
+# shellcheck disable=SC1090
+. "${DIR}"/tools/linux-install-docker || error_exit "Cannot load Docker install script"
+# shellcheck disable=SC1090
+. "${DIR}"/tools/linux-install-gcloud || error_exit "Cannot load gcloud install script"
+# shellcheck disable=SC1090
+. "${DIR}"/tools/linux-install-golang || error_exit "Cannot load golang install script"
+# shellcheck disable=SC1090
+. "${DIR}"/tools/linux-install-ninja || error_exit "Cannot load ninja install script"
+# shellcheck disable=SC1090
+. "${DIR}"/tools/linux-install-repo || error_exit "Cannot load repo install script"
+# shellcheck disable=SC1090
+. "${DIR}"/tools/linux-install-wrk || error_exit "Cannot load wrk install script"
+# shellcheck disable=SC1090
+. "${DIR}"/tools/linux-install-protoc || error_exit "Cannot load protoc install script"
+# shellcheck disable=SC1090
+. "${DIR}"/tools/linux-install-helm || error_exit "Cannot load helm install script"
+# shellcheck disable=SC1090
+. "${DIR}"/tools/linux-install-gcc || error_exit "Cannot load gcc install script"
 
 export DEBIAN_FRONTEND=noninteractive
 
@@ -61,6 +74,8 @@ function install_packages() {
 
 
 while getopts :b:p: arg; do
+  # shellcheck disable=SC2220
+  # shellcheck disable=SC2034
   case ${arg} in
     p) PLATFORM="${OPTARG}";;
     b) TOOLS_BUCKET="${OPTARG}";;
@@ -80,6 +95,7 @@ echo "Installing tools if necessary"
 if [[ -d "${TOOLS_DIR}" ]]; then
   [[ -n "${SUDO}" ]] && ${SUDO} chown -R "${USER}" "${TOOLS_DIR}"
 else
+  # shellcheck disable=SC2174
   mkdir -p "${TOOLS_DIR}" -m 0777
 fi
 update_docker "${PLATFORM}"
diff --git a/scripts/tools/linux-install-clang b/scripts/tools/linux-install-clang
--- a/scripts/tools/linux-install-clang
+++ b/scripts/tools/linux-install-clang
@@ -7,7 +7,8 @@ if [[ "$(uname)" != "Linux" ]]; then
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
 LLVM_VERSION=8
 
diff --git a/scripts/tools/linux-install-cmake b/scripts/tools/linux-install-cmake
--- a/scripts/tools/linux-install-cmake
+++ b/scripts/tools/linux-install-cmake
@@ -6,7 +6,8 @@ if [[ "$(uname)" != "Linux" ]]; then
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
 CMAKE_VERSION='3.8.0'
 CMAKE_BASE_URL="https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}"
diff --git a/scripts/tools/linux-install-helm b/scripts/tools/linux-install-helm
--- a/scripts/tools/linux-install-helm
+++ b/scripts/tools/linux-install-helm
@@ -6,7 +6,8 @@ if [[ "$(uname)" != "Linux" ]]; then
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+# shellcheck disable=SC1090
+. "${DIR}"/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
 HELM_VERSION='v2.7.2'
 HELM_BASE_URL="https://storage.googleapis.com/kubernetes-helm"
@@ -15,7 +16,7 @@ HELM_URL="${HELM_BASE_URL}/${HELM_ARCHIVE}"
 
 # Install helm cli
 function install_helm_cli() {
-    cd /tmp
+    cd /tmp || exit
     curl -Lo /tmp/helm.tgz ${HELM_URL}
     tar xfz helm.tgz
     mv linux-amd64/helm /usr/local/bin
