Update documentations and scripts for High Availability (#120)
* Create a script to prepare for upgrade.

Backups Jenkins configurations from currently running pod.
Instead of backing up the secrets in cloud storage from the SHA,
jenkins_home/creds.ref file is created and points to the archive
created.
Creates a snapshot of the disk use for Jenkins.

* Makes PD creation script more resilient

Adds more logging and error message.
Actually checkout the istio-testing at the given SHA
Update the way to get the secrets from cloud storage from
jenkins_home/creds.ref

* Update documentation

* Remove Table of content link

* Fixes typo

diff --git a/scripts/create_backup_pd b/scripts/create_backup_pd
--- a/scripts/create_backup_pd
+++ b/scripts/create_backup_pd
@@ -1,29 +1,40 @@
 #!/bin/bash
-set -ex
 
-TMP_DIR="$(mktemp -d /tmp/jkpd.XXXX)"
-ZONE='us-central1-f'
+SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+. ${SCRIPTS_DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+
 BUCKET='istio-tools/jenkins/images'
-SHA=""
-TOOL_BUCKET='istio-tools/jenkins-secrets'
 DISK='jenkins-home'
-
+OWNER='istio'
+SHA=""
+TMP_DIR="$(mktemp -d /tmp/jkpd.XXXX)"
+MNT_DIR="${TMP_DIR}/mnt"
+ZONE='us-central1-f'
 
 function usage () {
    cat <<EOF
-Usage: 
-    -z  Specify zone (Optional, default:us-central1-f)
+Usage:
     -b  Bucket name where backup disk be stored (Optional, default:istio-tools/jenkins/images)
+    -d  Name for backup disk (Optional, default:jenkins-home)
+    -o  Github Owner (Optional, default:istio)
     -s  SHA which collected jenkins secrets (Necessry)
-    -t  Bucket where secrets are stored (Optional, default:istio-tools/jenkins-secrets)
-    -d  Name for backup disk (Optional, default:jenkins-home) 
+    -z  Specify zone (Optional, default:us-central1-f)
 EOF
+exit 1
 }
 
 function disconnect {
-  if [[ -n ${LOOP_DEVICE} ]]; then 
-    { mount | grep ${LOOP_DEVICE}; } && sudo umount ${LOOP_DEVICE}
-    sudo losetup -d ${LOOP_DEVICE}
+  if [[ -n ${LOOP_DEVICE} ]]; then
+    # Checking if loop device is mounted
+    mount | grep ${LOOP_DEVICE}
+    if [[ ${?} -eq 0 ]]; then
+      ${SUDO} umount ${LOOP_DEVICE} \
+        || error_exit "Could not umount ${LOOP_DEVICE}"
+      echo ">>>>>>>>>>>>>>>>>>>> Unmounted ${LOOP_DEVICE}"
+    fi
+    ${SUDO} losetup -d ${LOOP_DEVICE} \
+      || error_exit "Could not delete loop device ${LOOP_DEVICE}"
+    echo ">>>>>>>>>>>>>>>>>>>> Deleted Loop device ${LOOP_DEVICE}"
     LOOP_DEVICE=''
   fi
 }
@@ -35,58 +46,85 @@ function cleanup {
 
 trap cleanup EXIT
 
-while getopts z:b:s:t:d:p:h arg; do
+while getopts :b:d:ho:s:z: arg; do
   case ${arg} in
-    z) ZONE="${OPTARG}";;
     b) BUCKET="${OPTARG}";;
-    s) SHA="${OPTARG}";;
-    t) TOOL_BUCKET="${OPTARG}";;
     d) DISK="${OPTARG}";;
     h) usage;;
+    o) OWNER="${OPTARG}";;
+    s) SHA="${OPTARG}";;
+    z) ZONE="${OPTARG}";;
     *) error_exit "Unrecognized argument ${OPTARG}";;
   esac
 done
 
-if ["$SHA" = ""]; then
+GITHUB_URL="https://github.com/${OWNER}/istio-testing"
+
+if ["${SHA}" = ""]; then
   error_exit 'Missing SHA for secrets. Please use -s'
 fi
 
-mkdir -p ${TMP_DIR}/mnt
+mkdir -p "${MNT_DIR}"
 
-cd ${TMP_DIR}
-dd if=/dev/zero of=disk.raw bs=1024k seek=102400 count=0
+cd "${TMP_DIR}"
+dd if=/dev/zero of=disk.raw bs=1024k seek=102400 count=0 \
+  || error_exit "Could not create raw disk image"
 echo '>>>>>>>>>>>>>>>>>>>> Created a blank image.'
 
-LOOP_DEVICE=$(sudo losetup -f) || { LOOP_DEVICE=''; error_exit 'Cannot get a loop device'; }
+LOOP_DEVICE="$(${SUDO} losetup -f)" \
+  || error_exit 'Cannot get a loop device'
 
-sudo losetup ${LOOP_DEVICE} disk.raw
+${SUDO} losetup "${LOOP_DEVICE}" disk.raw \
+  || error_exit 'Could not create a loop device with disk.raw'
 
-sudo mkfs.ext4 -F -E lazy_itable_init=0,lazy_journal_init=0 ${LOOP_DEVICE}
-echo '>>>>>>>>>>>>>>>>>>>> Format the block in ext4.'
+${SUDO} mkfs.ext4 -F -E lazy_itable_init=0,lazy_journal_init=0 "${LOOP_DEVICE}" \
+  || error_exit "Failed to format device ${LOOP_DEVICE}"
+echo '>>>>>>>>>>>>>>>>>>>> Formatted the block in ext4.'
 
-sudo mount ${LOOP_DEVICE} ${TMP_DIR}/mnt
-sudo chown -R ${USER} ${TMP_DIR}
+${SUDO} mount "${LOOP_DEVICE}" "${MNT_DIR}" \
+  || error_exit "Could not mount ${LOOP_DEVICE} to ${MNT_DIR}"
+[[ -n "${USER}" ]] && ${SUDO} chown -R ${USER} ${TMP_DIR} \
+  || error_exit 'Could not change permission on files'
+
 echo '>>>>>>>>>>>>>>>>>>>> Mounted to mnt.'
 
-gsutil cp gs://${TOOL_BUCKET}/secrets-${SHA}.tar.gz .
-tar -xvf secrets-${SHA}.tar.gz
-cp -R var/jenkins_home/secrets/* ${TMP_DIR}/mnt
+git clone "${GITHUB_URL}" \
+  || error_exit 'Failed to clone istio-testing'
+pushd istio-testing
+git reset --hard ${SHA} \
+  || error_exit 'Could not reset to ${SHA}'
+ARCHIVE="$(cat jenkins_home/creds.ref)"
+echo "Downloading secrets from ${ARCHIVE}"
+gsutil cp "${ARCHIVE}" - \
+  | tar -zxf - -C jenkins_home --strip-components=2 \
+  || error_exit 'Failed to copy jenkins secrets.'
+popd
 
-git clone https://github.com/istio/istio-testing
-cp -R istio-testing/jenkins_home/* ${TMP_DIR}/mnt/
-sudo chown -R 1000:1000 ${TMP_DIR}/mnt
+echo 'Copying content to disk'
+cp -R istio-testing/jenkins_home/* "${MNT_DIR}"/ \
+  || error_exit 'Failed to copy files'
+
+${SUDO} chown -R 1000:1000 "${MNT_DIR}"
 #Change owner to 'jenkins' whose uid and gid are 1000
 echo '>>>>>>>>>>>>>>>>>>>> Loaded source code to the image.'
 
 disconnect
 
-tar -cSzvf jenkins-home.tar.gz disk.raw
+tar -cSzvf jenkins-home.tar.gz disk.raw \
+  || error_exit 'Could not create archive'
 echo '>>>>>>>>>>>>>>>>>>>> Packaged the image.'
 
-gsutil cp jenkins-home.tar.gz gs://${BUCKET}/
+gsutil cp jenkins-home.tar.gz gs://${BUCKET}/ \
+  || error_exit 'Failed to copy arvice to cloud storage'
 echo '>>>>>>>>>>>>>>>>>>>> Uploaded to Cloud Storage.'
-gcloud compute images create ${DISK}-image --source-uri gs://${BUCKET}/jenkins-home.tar.gz
+
+gcloud compute images create ${DISK}-image --source-uri \
+  gs://${BUCKET}/jenkins-home.tar.gz \
+  || error_exit 'Failed to create disk image'
 echo '>>>>>>>>>>>>>>>>>>>> Created a CE image.'
-gcloud compute disks create ${DISK} --zone ${ZONE} --size 100 --image ${DISK}-image
+
+gcloud compute disks create ${DISK} \
+  --zone ${ZONE} --size 100 --image ${DISK}-image --type "pd-ssd" \
+  || error_exit 'Could not create disk'
 echo '>>>>>>>>>>>>>>>>>>>> Created a CE disk jenkins-home.'
 
